name: hflow
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - python=3.7.13
    - pytorch=1.12.0
    - torchvision=0.13.0
    - cudatoolkit=11.6
    - scipy=1.7.3
    - pip
    - tensorboard
    - h5py
    - pillow
    - matplotlib
    - ffmpeg
    - imageio
    - imageio-ffmpeg
    - pip:
       - -e .
